### ISSUE TITLE
Division by Zero Warning

### ISSUE THREAD

**Issue by Karlser1601** [khanamiryan/php-qrcode-detector-decoder#1]
Hi khanamiryan,

I get a infinite loop with following message:

" Warning : Division by zero in C : \ xampp \ htdocs \ qrcodereader \ lib \ common \ customFunctions.php on line 18 "

The GD Library and PHP version > = 5.3 is installed.

I am doing something specific wrong?

**Comment by khanamiryan** [comment]
Hi Karlser1601, I never before tested it on Windows.
Yes there was some problem with function overflow32, it was old and no need to use. 
Now it will working.
Please update files.
