### ISSUE TITLE
could you add composer.json for composer.install

### ISSUE THREAD

**Issue by bubifengyun** [khanamiryan/php-qrcode-detector-decoder#10]
now, many php projects support composer install, could you modify your code, and add such composer.json file.

thank you.

**Comment by gisostallenberg** [comment]
@khanamiryan shall I provide a pull request for you?

**Comment by JelleDijkhuizen** [comment]
I forked this repo and added composer support. Also I tried to clean up and do a bit of bug fixing.
[Click](https://github.com/JelleDijkhuizen/qrcodedecoder)

Hope you like it

**Comment by JelleDijkhuizen** [comment]
see #21
