### ISSUE TITLE
Can't decode this qrcode

### ISSUE THREAD

**Issue by itilev** [khanamiryan/php-qrcode-detector-decoder#112]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/5407537/139225861-398ccbbd-2bfd-4736-889b-878c10573888.png">

**Comment by karmendra** [comment]
Facing similar issues, unable to decode few QRs

**Comment by GenieTim** [comment]
If it does not work, you may want to use `$qrcode->text(['TRY_HARDER' => true]);` as seen in https://github.com/khanamiryan/php-qrcode-detector-decoder/blob/69c49a5960483e4c3d01214320f178c1a28bee79/tests/QrReaderTest.php#L32 for this specific QR-code.
