### ISSUE TITLE
packagist.org

### ISSUE THREAD

**Issue by mrmuminov** [khanamiryan/php-qrcode-detector-decoder#120]
![image](https://user-images.githubusercontent.com/64766486/158804553-1e16897b-aa4b-4bd6-9e71-4a7b2dff5fbf.png)
![image](https://user-images.githubusercontent.com/64766486/158804576-549e8898-3001-4c48-90d0-5d440dfbb1c9.png)

**Comment by MrMuminov** [comment]
Auto update not enabled

**Comment by GenieTim** [comment]
This is solved now.
