### ISSUE TITLE
Fatal error: Declaration of Zxing\GDLuminanceSource::isCropSupported() must be compatible with Zxing\LuminanceSource::isCropSupported(): bool in vendor\khanamiryan\qrcode-detector-decoder\lib\GDLuminanceSource.php on line 169

### ISSUE THREAD

**Issue by smrutiranjan7274** [khanamiryan/php-qrcode-detector-decoder#136]
Fatal error: Declaration of Zxing\GDLuminanceSource::isCropSupported() must be compatible with Zxing\LuminanceSource::isCropSupported(): bool in \vendor\khanamiryan\qrcode-detector-decoder\lib\GDLuminanceSource.php on line 169

Getting this error

My php version is  8.1.6
have enabled gd library extension

**Comment by rajucs** [comment]
any solution?

**Comment by domnicf** [comment]
> any solution?

try editing \vendor\khanamiryan\qrcode-detector-decoder\lib\LuminanceSource.php on line 64

from
public function isCropSupported(): bool
{
        return false;
}

to
public function isCropSupported()
{
        return false;
}

**Comment by hieuhidro** [comment]
You should edit here

barcode/vendor/khanamiryan/qrcode-detector-decoder/lib/GDLuminanceSource.php:169


```
//@Override
public function isCropSupported():bool
{
       return true;
}
```
