### ISSUE TITLE
throw new InvalidArgumentException must be prefixed with \ because of namespace?!

### ISSUE THREAD

**Issue by powtac** [khanamiryan/php-qrcode-detector-decoder#14]
There are around 25 occurrences of `throw new InvalidArgumentException` in the source code all of them within namespaced classes. So it should be `throw new \InvalidArgumentException`! Or am I wrong with something?

See http://stackoverflow.com/a/22664893/22470

One of my error messages:
`Fatal error: Class 'Zxing\Qrcode\Decoder\InvalidArgumentException' not found in /www/vendors/php-qrcode-detector-decoder/qrcode/decoder/Version.php on line 121`

**Comment by qhxin** [comment]
it is fixed in [this merge request](https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/20).
