### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by jamiedunns** [khanamiryan/php-qrcode-detector-decoder#16]
Hello, 

i started looking into this detector-decoder and it works really well for small images, the problem is once i get to bigger images, 

i want to be able to find a QR code within an image, for example if someone is holding a QR code while having their photo taken.

is there an know memory problem when using big images?

thank you
Jamie

**Comment by jamiedunns** [comment]
so in case anyone else ran into this problem i changed the size of the image object to a size it could read the qr code but not need huge amounts of memory.

QrReader.php:
if($isUseImagickIfAvailable && extension_loaded('imagick')) {
      $im=$this->scale($im,$im->getImageWidth(),$height = $im->getImageHeight());
      $width = $im->getImageWidth();
      $height = $im->getImageHeight();                
      $source = new \Zxing\IMagickLuminanceSource($im, $width, $height);
}

private function scale($im,$x,$y){
      if($x<$y){
            $im->scaleImage(0,800);
      } else {
            $im->scaleImage(800,0);
      }
      return $im;
}

**Comment by abesnier** [comment]
Thanks for the tip!
Have you observed a reduction of detection quality/result with this resizing?
