### ISSUE TITLE
Failed Install From Composer

### ISSUE THREAD

**Issue by ericariyanto** [khanamiryan/php-qrcode-detector-decoder#25]
@khanamiryan  hello, when i try install this plugin using composer with run this 

`composer require khanamiryan/qrcode-detector-decoder`

I got error, 

> [InvalidArgumentException]                                                                                                                                           
  Could not find package khanamiryan/qrcode-detector-decoder at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

How should i do?

**Comment by gofish543** [comment]
+1

**Comment by Branodolny** [comment]
same problem

**Comment by khanamiryan** [comment]
Now it works.
