### ISSUE TITLE
README wrong instructions

### ISSUE THREAD

**Issue by appfeel** [khanamiryan/php-qrcode-detector-decoder#26]
I've been spending some large minutes until I found it should be:

    $ composer require khanamiryan/qrcode-detector-decoder:dev-master

Otherwise it says no stable version found. I suppose that this will be happening until a release has been published in github.

**Comment by jugolm** [comment]
Thanks! Still not working, though. Now I get this:

The requested package khanamiryan/qrcode-detector-decoder No version set (parsed as 1.0.0) is satisfiable by khanamiryan/qrcode-detector-decoder[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by khanamiryan** [comment]
Now it will be work
