### ISSUE TITLE
Decode img from canvas

### ISSUE THREAD

**Issue by karlmendes** [khanamiryan/php-qrcode-detector-decoder#3]
I dont use yet ur lib, but one thing.... i used the camera of mobiles smartphones, to catch the QR Code and i input the file into a canvas..... I dont' know if this is possible, but its very nice if i can send (POST) the image into ur PHP and they answer me with the QRCode in text format... What do u thing about this ?

**Comment by khanamiryan** [comment]
There are good services to do that. For example http://zxing.org/w/decode.jspx or http://webqr.com/ .
This library doing another thing. It's for times when you cannot use camera and will use for example pictures in your library, directory etc.
