### ISSUE TITLE
Work with tmp_file

### ISSUE THREAD

**Issue by Jobel91** [khanamiryan/php-qrcode-detector-decoder#47]
I'm trying to use this library with a picture send by a form POST.
I don't want to save it to the server, and I want to use the temporary storage : 

```
$qrScreenPath = $_FILES['file']['tmp_name'];        
$qrcode = new Zxing\QrReader($qrScreenPath);
$text = $qrcode->text(); //return decoded text from QR Code
```

but I get this warning error : 

> imagecreatefromstring() : No JPEG support in this PHP build.

Does it a normal behavior of the library?

PS : I tried with a local picture, it works.

PHP 7
GD Library Enabled

**Comment by Jobel91** [comment]
I'm sorry, was a misconfiguration of my Docker container. This help me : https://stackoverflow.com/questions/47292221/troubles-with-docker-php7-gd-resulting-in-call-to-undefined-function-imagec

**Comment by hash9211** [comment]
Thank you for this, was stuck on this for hours. Your comment lead me to the proper solution to enable JPEG support in GD library in docker.
