### ISSUE TITLE
Missing class 'QRCodeDecoderMetaData' in lib\Qrcode\Decoder\Decoder.php line 135

### ISSUE THREAD

**Issue by garyjl** [khanamiryan/php-qrcode-detector-decoder#51]
Missing class 'QRCodeDecoderMetaData' in lib\Qrcode\Decoder\Decoder.php line 135, please advise me where this class is?

**Comment by karlcampbell** [comment]
I'm having the same issue, any luck here?

**Comment by LisenH** [comment]
Solved now？
