### ISSUE TITLE
Get content, this is return false

### ISSUE THREAD

**Issue by Tinywan** [khanamiryan/php-qrcode-detector-decoder#66]
HI! 
The QR code image cannot be expanded if it is enlarged.
```
$qrcode = new QrReader($file_path);
$qrcode->text() // return false
```
Get content, this is return `false`。How can I solve this?

### The following two are the same QR code
eg1: `success`
![1111](https://user-images.githubusercontent.com/14959876/58307033-05a8f680-7e30-11e9-9bd2-cc66b1f4d8ab.png)

eg2: `false`
![2222](https://user-images.githubusercontent.com/14959876/58307041-093c7d80-7e30-11e9-92b2-b3b1d915dc0f.png)

**Comment by powtac** [comment]
Probably the same as https://github.com/khanamiryan/php-qrcode-detector-decoder/issues/15

**Comment by Tinywan** [comment]
@powtac Thinks
