### ISSUE TITLE
psr4 autoload doesn't follow psr4 rules and won't work with composer 2

### ISSUE THREAD

**Issue by mmarton** [khanamiryan/php-qrcode-detector-decoder#85]
In the latest composer (1.10.0-rc) the following is shown:

Deprecation Notice: Class Zxing\Common\CharacterSetEci\AbstractEnum\AbstractEnum located in ./vendor/khanamiryan/qrcode-detector-decoder/lib/Common/AbstractEnum.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

(namespace and path mismatch)

It can be fixed by changing the namespace, moving it 1 folder deeper or adding the class to the files part in composer autoload.

M

**Comment by mmarton** [comment]
It already fixed in https://github.com/khanamiryan/php-qrcode-detector-decoder/commit/9fbe9fd20bdc8be6aade6ab50753b87c0709940c, just need a new release.

**Comment by aglipanci** [comment]
@khanamiryan can you release another version to include that change?

**Comment by mmarton** [comment]
fixed in 1.0.2
