### ISSUE TITLE
Needs PHP 8 support

### ISSUE THREAD

**Issue by francislavoie** [khanamiryan/php-qrcode-detector-decoder#98]
I'm using this library via https://github.com/endroid/qr-code and this is the only blocker for installing on PHP 8.

**Comment by Moskito89** [comment]
I created a PR for that: https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/101

**Comment by francislavoie** [comment]
Thanks @khanamiryan for merging!

**Comment by khanamiryan** [comment]
You are welcome. I would like to make more improvements, but don't have time to do.
